# Cops Configuration

# Master Switches (all features that can modify system state)
enable_spotlight: false # Spotlight indexing control - Important to note that if you use this particular module, a human must be present to type in the password!
enable_preferences: true # System preferences configuration
enable_tools: true # CLI tools installation
enable_aliases: true # Shell aliases configuration
enable_vim: true # Vim editor configuration
enable_file_assoc: true # File associations setup
enable_snapshots: true # Create APFS snapshot before changes
enable_brewbundle: true # Process Brewfiles for package installation

# User Information
user:
  name: "Shane Holloman"
  email: "shaneholloman@gmail.com"

# Paths and Directory Structure
paths:
  cops: "$HOME/.cops"
  oh_my_posh_theme: "$HOME/Dropbox/shane/conf/warpdeck.omp.json"

directories:
  - bin
  - config/git
  - config/zsh
  - config/vim
  - config/aws
  - config/terraform
  - config/k8s
  - scripts
  - .local/bin # Required for uv tool installations

# Development Environment
shell:
  default: "zsh"
  theme:
    type: "oh-my-posh"
    path: "~/Dropbox/shane/conf/warpdeck.omp.json"
  env_vars:
    AWS_CONFIG_FILE: "$HOME/.aws/config"
    AWS_SHARED_CREDENTIALS_FILE: "$HOME/.aws/credentials"
    KUBECONFIG: "$HOME/.kube/config"
    TERRAFORM_CONFIG: "$HOME/.terraform.d/config.tfrc"
    HOMEBREW_NO_ENV_HINTS: "1"

git:
  editor: "vim"
  default_branch: "main"
  pull_rebase: true
  color_ui: true
  auto_commit: true   # Automatically save your COPS configuration changes
  auto_push: true    # Set to true to also push changes to remote repo

vim:
  options:
    - "syntax on"
    - "set number"
    - "set ruler"
    - "set expandtab"
    - "set tabstop=2"
    - "set shiftwidth=2"
    - "set autoindent"
    - "set smartindent"
    - "set paste"
    - "set hlsearch"
    - "set incsearch"
    - "set cursorline"
  filetypes:
    yaml: "setlocal ts=2 sts=2 sw=2 expandtab"
    terraform: "setlocal ts=2 sts=2 sw=2 expandtab"
    json: "setlocal ts=2 sts=2 sw=2 expandtab"

# Package and Tool Management
brewbundle:
  install_types:
    formulas: true
    casks: true
    vscode: false
  paths:
    - "$COPS_ROOT/Brewfile"
    - "$HOME/.Brewfile"
    - "$HOME/Brewfile"

tools:
  cli:
    - ack
    - awscli
    - bash
    - bash-completion2
    - cmake
    - curl
    - fd
    - ffmpeg
    - findutils
    - fzf
    - gh
    - gmp
    - gnu-sed
    - gnupg
    - go
    - grep
    - helm
    - imagemagick
    - jq
    - kubernetes-cli
    - lazygit
    - libmagic
    - libreoffice
    - lua
    - lynx
    - moreutils
    - mpv
    - obs
    - oh-my-posh
    - openssh
    - p7zip
    - pandoc
    - php
    - pigz
    - pkgconf
    - portaudio
    - pv
    - rename
    - ripgrep
    - rlwrap
    - rust
    - screen
    - shellcheck
    - signal
    - terraform
    - tesseract
    - tree
    - uv
    - vlc
    - volta
    - yq
    - yt-dlp

  cask:
    - docker
    - claude
    - ollama
    - iterm2
    - dropbox
    - firefox
    - spotify
    - font-hack-nerd-font
    - powershell
    - visual-studio-code
    - visual-studio-code@insiders
    - vivaldi
    - sequel-ace

  forensic:
    # - aircrack-ng
    # - bfg
    # - binutils
    # - binwalk
    # - cifer
    # - dex2jar
    # - dns2tcp
    # - fcrackzip
    # - foremost
    # - hashpump
    # - hydra
    # - john
    # - knock
    # - netpbm
    # - nmap
    # - pngcheck
    # - socat
    # - sqlmap
    # - tcpflow
    # - tcpreplay
    # - tcptrace
    # - ucspi-tcp
    # - xpdf
    # - xz

# Aliases
# Command using escaped characters in YAML:
# - Double backslash (\\) is needed for YAML to preserve single backslash
# - Double quotes (\") are needed to preserve quotes in shell
# - When set as alias, becomes: path='echo $PATH | tr ":" "\n"'
# Also, dont use inline comments in this section, it will break yaml parsing when we add to the shell

aliases:
  navigation:
    dropbox: "cd ~/Dropbox"
    "..": "cd .."
    "...": "cd ../.."
    "....": "cd ../../.."
    dl: "cd ~/Downloads"
    dt: "cd ~/Desktop"
    docs: "cd ~/Documents"
    p: "cd ~/Projects"
    d: "cd ~/Dropbox"

  common_utils:
    a: "alias"
    ls: "ls -G"
    ll: "ls -lah"
    grep: "grep --color=auto"
    fgrep: "fgrep --color=auto"
    egrep: "egrep --color=auto"
    path: "echo $PATH | tr \":\" \"\\n\""
    ports: "sudo lsof -iTCP -sTCP:LISTEN -P"
    pubkey: "cat ~/.ssh/id_rsa.pub | pbcopy"
    week: "date +%V"

  git:
    g: "git"
    gb: "git branch"
    gc: "git commit"
    gco: "git checkout"
    gd: "git diff"
    gi: "git init -b main"
    gl: "git pull"
    gp: "git push"
    gs: "git status"

  docker:
    dk: "docker"
    dkc: "docker compose"
    dkp: "docker ps"
    dki: "docker images"

  development:
    py: "python3"
    pip: "pip3"
    serve: "python3 -m http.server"

# System Configuration
preferences:
  # Group switches (all default: false for safety)
  enable_groups:
    terminal: true
    security: false
    input: false
    finder: false
    dock: false
    safari: false
    global: false
    activity: false

  # Terminal preferences
  terminal:
    iterm2:
      "Normal Font": "Hack Nerd Font Mono 12"
    global:
      KeyRepeat: 1
      InitialKeyRepeat: 10
      ApplePressAndHoldEnabled: false

  # Finder preferences
  finder:
    finder:
      ShowPathbar: true
      ShowStatusBar: true
      AppleShowAllFiles: false
      _FXSortFoldersFirst: true
      FXDefaultSearchScope: "SCcf"

  # Dock preferences
  dock:
    dock:
      autohide: true
      tilesize: 48
      mineffect: "scale"

  # Input preferences
  input:
    trackpad:
      Clicking: true
      TrackpadThreeFingerDrag: true
    global:
      "com.apple.mouse.scaling": 2.0
      "com.apple.trackpad.scaling": 1.5

  # Security preferences
  security:
    screensaver:
      askForPassword: 1
      askForPasswordDelay: 0

# File and Application Configuration
file_associations:
  editor:
    bundle_id: "com.microsoft.VSCodeInsiders"
  extensions:
    - "py" # Python
    - "js" # JavaScript
    - "ts" # TypeScript
    - "css" # CSS
    - "json" # JSON
    - "md" # Markdown
    - "xml" # XML
    - "yaml" # YAML
    - "yml" # YAML
    - "sh" # Shell scripts

# Spotlight Configuration
spotlight:
  # Note: This module requires human interaction to enter sudo password!
  indexing:
    external_volumes: false # When true, enables indexing for all external volumes; when false, disables

# Restore Configuration
# the back path needs to be reviewed and confirmed as compatible with the system and our project!!
restore:
  paths:
    mount_point: "/tmp/snap"
    disk_device: "/dev/disk3s5"
    user_home: "$HOME"
    root: "/"
    backup_dir_prefix: ".cops_backup_"
  files:
    cops:
      - ".zshrc"
      - ".bashrc"
      - ".gitconfig"
    config_dirs:
      - ".config"
      - ".aws"
      - ".terraform.d"
      - ".kube"
      - ".vscode-insiders"
